/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TournamentsSlugRouteImport } from './routes/tournaments/$slug'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsSlugRoute = TournamentsSlugRouteImport.update({
  id: '/tournaments/$slug',
  path: '/tournaments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/teams': typeof TeamsRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/tournaments/': typeof TournamentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/teams': typeof TeamsRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/tournaments': typeof TournamentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/teams': typeof TeamsRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/tournaments/': typeof TournamentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/teams' | '/tournaments/$slug' | '/tournaments/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/teams' | '/tournaments/$slug' | '/tournaments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/teams'
    | '/tournaments/$slug'
    | '/tournaments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TeamsRoute: typeof TeamsRoute
  TournamentsSlugRoute: typeof TournamentsSlugRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$slug': {
      id: '/tournaments/$slug'
      path: '/tournaments/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof TournamentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TeamsRoute: TeamsRoute,
  TournamentsSlugRoute: TournamentsSlugRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
